input:

    image_dir: '/gpfs/mnt/gpfs01/astro/workarea/esheldon/lensing/des-lensing/psfsim/v009/output'
    images: 'psfsim-stars-v009-000000.fits'
    image_hdu: 0
    badpix_hdu: 1
    weight_hdu: 2

    cat_dir: '/astro/u/mjarvis/work/sims/psfsim-stars-v009/v01'
    cats: 'psfsim-stars-v009-000000_psfcat.fits'
    cat_hdu: 2

    x_col: XWIN_IMAGE
    y_col: YWIN_IMAGE
    sky_col: BACKGROUND
    ra: TELRA
    dec: TELDEC
    gain: 4.0
    #noise: 469.  # Variance in ADU per pixel.
    #sky: 231.    # Sky level in ADU per pixel.

    stamp_size: 25
    #nstars: 50

output:
    dir: '/astro/u/mjarvis/work/sims/psfsim-stars-v009/v04'
    file_name: 'psfsim-stars-v009-000000_piff.fits'

psf:

    model:
        type: PixelGrid
        scale: 0.20
        size: 17
        start_sigma: 0.8  # The code is pretty robust to this being larger than the actual size
                          # of the PSF, but if it's much smaller, then there can be problems.

    interp:
        type: BasisPolynomial
        #type: Polynomial
        order: 3

    outliers:
        type: Chisq
        nsigma: 4
        max_remove: 3

verbose: 2
